# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # registry-url: 'https://registry.npmjs.org'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jeysonj2'
          cache: 'npm'
      - run: npx playwright install-deps
      - run: npm ci
      # - run: npm run verify
      - run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          npm version prerelease --preid=next
      - run: npm publish --tag next --access public
      - run: git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_GITHUB_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
